// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PixelRealms.Persistence.Ef;

#nullable disable

namespace PixelRealms.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20261006120000_CharacterSpellUpgrades")]
    partial class CharacterSpellUpgrades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PixelRealms.Persistence.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_username_ci");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint")
                        .HasColumnName("gold");

                    b.Property<int>("Hp")
                        .HasColumnType("integer")
                        .HasColumnName("hp");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("map_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.Property<int>("Resource")
                        .HasColumnType("integer")
                        .HasColumnName("resource");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<float>("X")
                        .HasColumnType("real")
                        .HasColumnName("x");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.Property<float>("Y")
                        .HasColumnType("real")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_characters_account_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_name_ci");

                    b.ToTable("characters", null, t =>
                        {
                            t.HasCheckConstraint("ck_characters_level", "level BETWEEN 1 AND 15");
                        });
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.CharacterCooldown", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("Ref")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("ref");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.HasKey("CharacterId", "Kind", "Ref")
                        .HasName("pk_character_cooldowns");

                    b.ToTable("character_cooldowns", (string)null);
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.CharacterHotbarSlot", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<short>("Slot")
                        .HasColumnType("smallint")
                        .HasColumnName("slot");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("ref");

                    b.HasKey("CharacterId", "Slot")
                        .HasName("pk_character_hotbar");

                    b.ToTable("character_hotbar", (string)null);
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.CharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<short>("Container")
                        .HasColumnType("smallint")
                        .HasColumnName("container");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<short>("Slot")
                        .HasColumnType("smallint")
                        .HasColumnName("slot");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_character_items");

                    b.HasIndex("CharacterId", "Container", "Slot")
                        .IsUnique()
                        .HasDatabaseName("ix_character_items_character_id_container_slot");

                    b.ToTable("character_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_items_quantity", "quantity >= 1");
                        });
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.CharacterSpellUpgrade", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("SpellId")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("spell_id");

                    b.Property<string>("UpgradeId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("upgrade_id");

                    b.HasKey("CharacterId", "SpellId")
                        .HasName("pk_character_spell_upgrades");

                    b.ToTable("character_spell_upgrades", (string)null);
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.ItemAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<Guid?>("CounterpartyCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_character_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_item_audit_log");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_item_audit_log_character_id");

                    b.ToTable("item_audit_log", (string)null);
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.Character", b =>
                {
                    b.HasOne("PixelRealms.Persistence.Entities.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.CharacterCooldown", b =>
                {
                    b.HasOne("PixelRealms.Persistence.Entities.Character", null)
                        .WithMany("Cooldowns")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_cooldowns_characters_character_id");
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.CharacterHotbarSlot", b =>
                {
                    b.HasOne("PixelRealms.Persistence.Entities.Character", null)
                        .WithMany("Hotbar")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_hotbar_characters_character_id");
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.CharacterItem", b =>
                {
                    b.HasOne("PixelRealms.Persistence.Entities.Character", null)
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_items_characters_character_id");
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.CharacterSpellUpgrade", b =>
                {
                    b.HasOne("PixelRealms.Persistence.Entities.Character", null)
                        .WithMany("SpellUpgrades")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_spell_upgrades_characters_character_id");
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.Account", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("PixelRealms.Persistence.Entities.Character", b =>
                {
                    b.Navigation("Cooldowns");

                    b.Navigation("Hotbar");

                    b.Navigation("Items");

                    b.Navigation("SpellUpgrades");
                });
#pragma warning restore 612, 618
        }
    }
}
