<Project Sdk="Microsoft.NET.Sdk.Web">
  <!-- Host ASP.NET Core: REST auth/personajes, WebSocket, GameLoop. -->
  <PropertyGroup>
    <UserSecretsId>pixelrealms-server</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PixelRealms.Protocol/PixelRealms.Protocol.csproj" />
    <ProjectReference Include="../PixelRealms.Content/PixelRealms.Content.csproj" />
    <ProjectReference Include="../PixelRealms.Game/PixelRealms.Game.csproj" />
    <ProjectReference Include="../PixelRealms.Persistence/PixelRealms.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!-- Solo para `dotnet ef` (migraciones); no se publica. -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
